name: Build Void package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/void-linux/void-glibc-full

    steps:
      - name: Install Git
        run: |
          xbps-install -Syu
          xbps-install -y git

      - name: Checkout void-packages
        uses: actions/checkout@v4

      - name: Bootstrap build environment
        run: |
          ./xbps-src binary-bootstrap

      - name: Build libraw
        run: |
          ./xbps-src pkg libraw

      - name: Upload XBPS package
        uses: actions/upload-artifact@v4
        with:
          name: libraw-xbps
          path: hostdir/binpkgs/**/*.xbps
